import type { AppProps } from 'next/app';
import Head from 'next/head';
import { FormProvider } from '../../contexts';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Entertainment app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      </Head>
      <FormProvider>
        <Component {...pageProps} />
      </FormProvider>
    </>
  );
}
